# Generated by Django 4.2.9 on 2024-04-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_remove_post_likes_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='favs',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
