# Generated by Django 4.2.9 on 2024-04-13 12:53

from django.db import migrations

def create_members(apps, schema_editor):
    User = apps.get_model('network', 'User')
    Member = apps.get_model('network', 'Member')
    user_obj = User.objects.filter()
    users = user_obj.all()
    for user in users:
        try:
            Member.objects.get(user=user)
            pass
        except (KeyError, Member.DoesNotExist):
            Member.objects.create(user=user)

class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_alter_post_date'),
    ]

    operations = [
        migrations.RunPython(create_members),
    ]
